### ISSUE TITLE
add list consteagle

### ISSUE THREAD

**Issue by LucasB25** [botblock/data#13]
Hello I would like to add this list to bot list 

https://consteagle.com
https://discord.gg/Mwjk8dVUQJ

**Comment by renhiyama** [comment]
Just add it yourself. Make a pull request

**Comment by LucasB25** [comment]
How? 'Or' What ?

**Comment by MattIPv4** [comment]
Create a pull request adding your list information as a new JSON file in `data/lists`, following the JSON schema at `schema/list.json`.

**Comment by MattIPv4** [comment]
No progress, closing.
