### ISSUE TITLE
bladebotlist.xyz -> bladelist.gg

### ISSUE THREAD

**Issue by EndBug** [botblock/data#21]
Hey, I've noticed that BotBlock still displays BladeList as BladeBotList (all endpoints have changed too)
I can open a PR, I was just wondering if I had to add something to record the previous name and/or URL
If I don't have to add anything I'll change everything referencing the old website and name

**Comment by MattIPv4** [comment]
A PR to update it all would be great -- the only thing that needs to be added would be a legacy ID entry if you change the actual list ID: https://github.com/botblock/data/blob/master/data/legacy.json

**Comment by EndBug** [comment]
Got it 👍🏻

**Comment by HiiZun** [comment]
Hello i've done an update for bladelist.gg check out pull requests

**Comment by MattIPv4** [comment]
https://github.com/botblock/data/commit/39d1214405d2fc14843d6a2668ec35ebfb3db154
