### ISSUE TITLE
How add a botlist?

### ISSUE THREAD

**Issue by andrelucaas** [botblock/data#22]
> Hello, I am the owner of the botlist "bots de discord", I would like to know how to add a botlist to the list, I already searched and didn't find any place about it.
- Open-Source: https://github.com/botsddiscord/botsdediscord
- Website: https://botsdediscord.herokuapp.com

**Comment by MattIPv4** [comment]
👋 Please open a PR adding your list information in a new file within the `data/lists` directory, following the schema found in `schema/list.json`
