### ISSUE TITLE
Test data validation

### ISSUE THREAD

**Issue by anshtyagi0** [botblock/data#87]
As discord changes new usernames from username#discriminator to username from now so it cause issue when changing it to the new username as it requires discriminator too.
Please fix that so that we can add new usernames instead of that old one.

**Comment by MattIPv4** [comment]
You can use `#0000` as the discrim. I have no intention to change the validation for now, so that it is explicit whether a username has a discrim, or not, rather than it just being that someone may have forgotten to include it.
